# Generated by Django 2.2.1 on 2019-07-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_auto_20190630_1722'),
        ('reservas', '0008_delete_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pk_numpago', models.AutoField(primary_key=True, serialize=False)),
                ('t_fechapago', models.DateTimeField(auto_now=True)),
                ('i_subtotalpago', models.IntegerField()),
                ('i_totalpago', models.IntegerField()),
                ('i_puntosganados', models.IntegerField()),
                ('v_metodopago', models.CharField(max_length=50)),
                ('fk_cliente', models.ForeignKey(db_column='fk_cliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
                ('fk_reserva', models.ForeignKey(blank=True, db_column='fk_reserva', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva')),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
            },
        ),
    ]
