# Generated by Django 2.2.1 on 2019-05-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('v_estado', models.CharField(max_length=50)),
                ('d_proyeccion', models.DateField()),
                ('t_inicioproyeccion', models.TimeField()),
                ('t_finproyeccion', models.TimeField()),
            ],
            options={
                'db_table': 'funcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('v_nombre', models.CharField(max_length=150)),
                ('i_duracion', models.IntegerField()),
                ('tx_sinapsis', models.TextField()),
                ('v_foto', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'pelicula',
                'managed': False,
            },
        ),
    ]
