# Generated by Django 2.2.1 on 2019-06-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multiplex', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_nombre', models.CharField(max_length=150, verbose_name='nombre pelicula')),
                ('i_duracion', models.IntegerField(verbose_name='duracion pelicula')),
                ('tx_sinapsis', models.TextField(verbose_name='sinapsis pelicula')),
                ('v_foto', models.ImageField(upload_to='fotos-peliculas/', verbose_name='foto pelicula')),
            ],
            options={
                'db_table': 'pelicula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], max_length=50, verbose_name='estado de la funcion')),
                ('d_proyeccion', models.DateField(verbose_name='dia de proyeccion')),
                ('t_inicioproyeccion', models.TimeField(verbose_name='hora de inicio')),
                ('t_finproyeccion', models.TimeField(verbose_name='hora de finalizacion')),
                ('fk_pelicula', models.ForeignKey(db_column='fk_pelicula', on_delete=django.db.models.deletion.CASCADE, to='funciones.Pelicula', verbose_name='pelicula de la funcion')),
            ],
            options={
                'db_table': 'funcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FuncionSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_funcion', models.ForeignKey(db_column='fk_funcion', on_delete=django.db.models.deletion.CASCADE, to='funciones.Funcion')),
                ('fk_sala', models.ForeignKey(db_column='fk_sala', on_delete=django.db.models.deletion.CASCADE, to='multiplex.Sala')),
            ],
            options={
                'db_table': 'funcion_sala',
                'managed': True,
                'unique_together': {('fk_funcion', 'fk_sala')},
            },
        ),
    ]
