# Generated by Django 2.2.1 on 2019-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('v_tipocontrato', models.CharField(max_length=100)),
                ('d_iniciocontrato', models.DateField()),
                ('i_salario', models.IntegerField()),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
    ]
