# Generated by Django 2.2.1 on 2019-07-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fk_contrato',
        ),
    ]
