# Generated by Django 2.2.1 on 2019-06-29 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='v_primerapellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='v_primernombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='v_segundoapellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='v_segundonombre',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fk_persona',
            field=models.OneToOneField(db_column='fk_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
