# Generated by Django 2.2.1 on 2019-06-30 16:17

from django.db import migrations, models
import usuarios.managers


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190629_2116'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='persona',
            managers=[
                ('objects', usuarios.managers.PersonaManager()),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='d_fechapuntos',
            field=models.DateField(max_length=50, verbose_name='fecha expiracion puntos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='i_numpuntos',
            field=models.IntegerField(verbose_name='Numero de puntos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='i_numtarjeta',
            field=models.CharField(max_length=50, verbose_name='Numero tarjeta preferente'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='i_telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pk_cedula',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='v_direccion',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
    ]
