# Generated by Django 2.2.1 on 2019-06-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190630_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='d_fechapuntos',
            field=models.DateField(blank=True, max_length=50, verbose_name='fecha expiracion puntos'),
        ),
    ]
