# Generated by Django 2.2.1 on 2019-06-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20190630_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='d_fechapuntos',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='fecha expiracion puntos'),
        ),
    ]
