# Generated by Django 2.2.1 on 2019-05-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multiplex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('v_nombre', models.CharField(max_length=100)),
                ('v_direccion', models.CharField(max_length=100)),
                ('v_ciudad', models.CharField(max_length=100)),
                ('i_minsalas', models.IntegerField()),
                ('i_maxsalas', models.IntegerField()),
            ],
            options={
                'db_table': 'multiplex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_numpreferencial', models.IntegerField()),
                ('i_numgeneral', models.IntegerField()),
            ],
            options={
                'db_table': 'sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('pk_numero', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('v_tipo', models.CharField(max_length=50)),
                ('i_orden', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'silla',
                'managed': False,
            },
        ),
    ]
