# Generated by Django 2.2.1 on 2019-06-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multiplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_nombre', models.CharField(max_length=100)),
                ('v_direccion', models.CharField(max_length=100)),
                ('v_ciudad', models.CharField(max_length=100)),
                ('i_minsalas', models.IntegerField()),
                ('i_maxsalas', models.IntegerField()),
            ],
            options={
                'db_table': 'multiplex',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_numsala', models.IntegerField()),
                ('i_numpreferencial', models.IntegerField()),
                ('i_numgeneral', models.IntegerField()),
                ('fk_multiplex', models.ForeignKey(db_column='fk_multiplex', on_delete=django.db.models.deletion.CASCADE, to='multiplex.Multiplex')),
            ],
            options={
                'db_table': 'sala',
                'managed': True,
                'unique_together': {('i_numsala', 'fk_multiplex')},
            },
        ),
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_numero', models.CharField(max_length=3)),
                ('v_tipo', models.CharField(choices=[('preferencial', 'Preferencial'), ('general', 'General')], max_length=50)),
                ('i_orden', models.CharField(max_length=50)),
                ('fk_sala', models.ForeignKey(db_column='fk_sala', on_delete=django.db.models.deletion.CASCADE, to='multiplex.Sala')),
            ],
            options={
                'db_table': 'silla',
                'managed': True,
                'unique_together': {('pk_numero', 'fk_sala')},
            },
        ),
    ]
