# Generated by Django 2.2.1 on 2019-06-29 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multiplex', '0001_initial'),
        ('snacks', '__first__'),
        ('usuarios', '__first__'),
        ('funciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_estado', models.CharField(max_length=50)),
                ('t_inicioreserva', models.TimeField()),
                ('fk_persona', models.ForeignKey(db_column='fk_persona', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reserva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SnackReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_cantidad', models.IntegerField()),
                ('fk_reserva', models.ForeignKey(db_column='fk_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.Reserva')),
                ('fk_snack', models.ForeignKey(db_column='fk_snack', on_delete=django.db.models.deletion.DO_NOTHING, to='snacks.Snack')),
            ],
            options={
                'db_table': 'snack_reserva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SillaReservada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_estado', models.CharField(choices=[('proceso', 'En proceso'), ('reservada', 'Reservada')], max_length=50)),
                ('fk_funcion_sala', models.ForeignKey(db_column='fk_funcion_sala', on_delete=django.db.models.deletion.CASCADE, to='funciones.FuncionSala')),
                ('fk_reserva', models.ForeignKey(db_column='fk_reserva', on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva')),
                ('fk_silla', models.ForeignKey(db_column='fk_silla', on_delete=django.db.models.deletion.CASCADE, to='multiplex.Silla')),
            ],
            options={
                'db_table': 'silla_reservada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pk_numpago', models.AutoField(primary_key=True, serialize=False)),
                ('t_fechapago', models.DateTimeField()),
                ('i_subtotalpago', models.IntegerField()),
                ('i_totalpago', models.IntegerField()),
                ('i_puntosganados', models.IntegerField()),
                ('v_metodopago', models.CharField(max_length=50)),
                ('fk_cliente', models.ForeignKey(db_column='fk_cliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
                ('fk_reserva', models.ForeignKey(blank=True, db_column='fk_reserva', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva')),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
            },
        ),
    ]
