# Generated by Django 2.2.1 on 2019-06-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pk_numpago', models.AutoField(primary_key=True, serialize=False)),
                ('t_fechapago', models.DateTimeField()),
                ('i_subtotalpago', models.IntegerField()),
                ('i_totalpago', models.IntegerField()),
                ('i_puntosganados', models.IntegerField()),
                ('v_metodopago', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnackReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'snack_reserva',
                'managed': False,
            },
        ),
    ]
