# Generated by Django 2.2.1 on 2019-07-12 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20190629_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillareservada',
            name='fk_funcion_sala',
            field=models.ForeignKey(db_column='fk_funcion_sala', on_delete=django.db.models.deletion.CASCADE, related_name='funsalas', to='funciones.FuncionSala'),
        ),
        migrations.AlterField(
            model_name='snackreserva',
            name='fk_reserva',
            field=models.ForeignKey(db_column='fk_reserva', on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva'),
        ),
        migrations.AlterField(
            model_name='snackreserva',
            name='fk_snack',
            field=models.ForeignKey(db_column='fk_snack', on_delete=django.db.models.deletion.CASCADE, to='snacks.Snack'),
        ),
    ]
