# Generated by Django 2.2.1 on 2019-07-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20190713_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='t_inicioreserva',
            field=models.DateField(auto_now_add=True),
        ),
    ]
