# Generated by Django 2.2.1 on 2019-07-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_auto_20190715_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='t_inicioreserva',
            field=models.DateTimeField(),
        ),
    ]
