# Generated by Django 2.2.1 on 2019-07-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_auto_20190721_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
